version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/my-app/app
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 8081      
    depends_on:
      - redis
  redis: 
    image: "redis:alpine"    