name: test

on: pull_request

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Node.js setup
              uses: actions/setup-node@v3
              with:
                node-version: "18"
            - name: Install yarn packages
              run: yarn install --immutable --immutable-cache --check-cache
            - name: install and run redis-server
              run:
                sudo apt-get update
                && sudo apt-get install -y redis-server
                && redis-server --daemonize yes --requirepass test_env --port 6380
            - name: Run test
              run: yarn run test:ci
            
            - name: test build
              run: yarn run build